import fs from 'fs';
import path from 'path';

// Complete dataset generator for 500 Indian recipes
const outputDir = path.join(process.cwd(), 'src', 'data', 'indianRecipes');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Master Raw Data Generator
const RAW_REGIONS = [
  // 1. SOUTH INDIA (Andhra Pradesh, Telangana, Tamil Nadu, Kerala, Karnataka)
  {
    region: 'South Indian',
    states: [
      {
        state: 'Andhra Pradesh',
        cuisine: 'Andhra Cuisine',
        items: [
          { name: 'Gongura Mamsam', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Very Hot', protein: 34, cal: 460, alt: ['Gongura Mutton'], desc: 'Tender mutton pieces slow cooked in a tangy, spicy puree of fresh red sorrel (gongura) leaves and Guntur red chillies.' },
          { name: 'Gongura Pachadi', cat: 'Chutneys', sub: 'Pickles', veg: true, vegan: true, spice: 'Very Hot', protein: 3, cal: 110, alt: ['Andhra Gongura Pickle'], desc: 'Iconic Andhra spicy and tangy condiment made with sautéed sorrel leaves, roasted red chillies, garlic, and fenugreek.' },
          { name: 'Andhra Kodi Kura', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Hot', protein: 36, cal: 380, alt: ['Andhra Chicken Curry'], desc: 'Rustic chicken curry cooked in an aromatic gravy of poppy seeds, coconut, and fiery Guntur chillies.' },
          { name: 'Gutti Vankaya Kura', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 7, cal: 275, alt: ['Andhra Stuffed Brinjal Curry'], desc: 'Baby eggplants stuffed with a roasted spice paste of peanuts, sesame seeds, coconut, and tamarind.' },
          { name: 'Chintapandu Pulihora', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 6, cal: 340, alt: ['Andhra Tamarind Rice', 'Prasadam Pulihora'], desc: 'Temple-style tangy tamarind rice tempered with peanuts, chana dal, mustard, ginger, green chillies, and curry leaves.' },
          { name: 'Pesarattu Upma', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: true, spice: 'Medium', protein: 14, cal: 310, alt: ['MLA Pesarattu', 'Green Moong Dal Crepe'], desc: 'Crispy whole green gram crepe stuffed with savoury semolina upma, served with allam pachadi (ginger chutney).' },
          { name: 'Royyala Vepudu', cat: 'Seafood', sub: 'Fish', veg: false, spice: 'Hot', protein: 30, cal: 260, alt: ['Andhra Prawn Fry'], desc: 'Succulent prawns pan-roasted with sliced onions, ginger-garlic, curry leaves, crushed black pepper, and spicy red masala.' },
          { name: 'Andhra Tomato Pappu', cat: 'Dal', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 11, cal: 210, alt: ['Tamata Pappu'], desc: 'Hearty yellow toor dal stewed with ripe tomatoes, green chillies, and finished with a sizzling garlic-mustard-curry leaf tadka.' },
          { name: 'Pootharekulu', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 2, cal: 220, alt: ['Paper Sweet', 'Atreyapuram Pootharekulu'], desc: 'Wafer-thin edible rice paper rolled with warm desi ghee, jaggery powder, cardamom, and chopped dry fruits.' },
          { name: 'Bobbatlu', cat: 'Sweets', sub: 'Roti & Paratha', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 290, alt: ['Andhra Bakshalu', 'Sweet Lentil Flatbread'], desc: 'Melt-in-mouth sweet flatbread filled with cooked chana dal, jaggery, cardamom, and nutmeg, roasted in ghee.' },
          { name: 'Ulava Charu', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 9, cal: 160, alt: ['Horsegram Soup Andhra Style'], desc: 'Earthy, nutrient-rich brown soup made from slow-boiled horsegram reduction, tamarind, and aromatic spices.' },
          { name: 'Kandi Podi Rice', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 8, cal: 280, alt: ['Gunpowder Dal Rice'], desc: 'Steamed rice mixed with roasted spiced toor and chana dal powder, dry red chillies, cumin, and generous hot melted ghee.' },
          { name: 'Chepala Pulusu', cat: 'Curries', sub: 'Fish', veg: false, spice: 'Hot', protein: 28, cal: 310, alt: ['Nellore Fish Curry'], desc: 'Tangy and spicy Nellore-style fish curry simmered in raw tamarind gravy with fenugreek and shallots.' },
          { name: 'Natu Kodi Pulusu', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Very Hot', protein: 38, cal: 420, alt: ['Country Chicken Curry'], desc: 'Traditional country chicken slow cooked with bone marrow flavor in a fiery red gravy with coriander and cloves.' },
          { name: 'Bendakaya Pulusu', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 4, cal: 180, alt: ['Okra Tamarind Stew'], desc: 'Tender okra batons cooked in a sweet-sour tamarind gravy with jaggery and mustard seasoning.' },
          { name: 'Aratikaya Vepudu', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 3, cal: 170, alt: ['Raw Banana Fry Andhra Style'], desc: 'Crispy raw plantain cubes shallow-fried with curry leaves, mustard seeds, and spiced roasted lentil powder.' },
          { name: 'Kakarakaya Vepudu', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 4, cal: 160, alt: ['Crispy Bitter Gourd Fry'], desc: 'Thinly sliced bitter gourd roasted crisp with onions, garlic, peanuts, and red chilli powder.' },
          { name: 'Dosakaya Pappu', cat: 'Dal', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 10, cal: 200, alt: ['Yellow Cucumber Dal'], desc: 'Comforting toor dal cooked with tart yellow cucumber cubes, turmeric, and cumin-garlic tadka.' },
          { name: 'Majjiga Pulusu', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 140, alt: ['Andhra Buttermilk Stew', 'Moru Curry'], desc: 'Spiced buttermilk soup tempered with mustard seeds, ginger, green chillies, and soaked bottle gourd cubes.' },
          { name: 'Kobbari Pachadi', cat: 'Chutneys', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 3, cal: 140, alt: ['Fresh Coconut Chutney Andhra Style'], desc: 'Stone-ground fresh coconut relish with roasted green chillies, cumin, and lemon juice.' },
          { name: 'Dondakaya Vepudu', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 3, cal: 150, alt: ['Ivy Gourd Fry', 'Tindora Fry'], desc: 'Pan-roasted ivy gourd discs tossed with crushed peanuts, roasted sesame, and garlic chilli masala.' },
          { name: 'Panakam', cat: 'Drinks', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 1, cal: 90, alt: ['Spiced Jaggery Cooler'], desc: 'Sacred festive cooler prepared with dissolved organic jaggery, crushed black pepper, dry ginger powder, and cardamom.' },
          { name: 'Kakinada Kaja', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 320, alt: ['Gotta Kaja'], desc: 'Crispy layered flour pastry deep fried and soaked in cardamom sugar syrup with juicy soft interiors.' },
          { name: 'Bandar Laddu', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 310, alt: ['Thokkudu Laddu'], desc: 'Famous Machilipatnam sweet made by pounding roasted gram flour sev with sugar syrup and ghee into smooth melt-in-mouth balls.' },
          { name: 'Madugula Halwa', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 360, alt: ['Wheat Milk Halwa'], desc: 'Traditional wheat milk halwa slow-stirred with cashew nuts, pure ghee, and jaggery for hours.' },
          { name: 'Atukula Upma', cat: 'Breakfast', sub: 'Snacks', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 210, alt: ['Andhra Poha Upma'], desc: 'Soft flattened rice tempered with mustard, roasted peanuts, ginger, green chillies, and fresh lemon juice.' },
          { name: 'Gongura Royyalu', cat: 'Seafood', sub: 'Fish', veg: false, spice: 'Very Hot', protein: 32, cal: 310, alt: ['Prawns in Sorrel Leaves Gravy'], desc: 'Plump prawns cooked in a tangy sorrel leaves gravy with shallots, garlic, and fiery Guntur chillies.' },
          { name: 'Miriyala Charu', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Hot', protein: 2, cal: 60, alt: ['Pepper Rasam Andhra Style'], desc: 'Traditional hot pepper rasam infused with crushed black peppercorns, cumin, garlic, and tamarind extract.' },
          { name: 'Senaga Pappu Payasam', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 260, alt: ['Chana Dal Kheer', 'Sweet Dal Pudding'], desc: 'Rich dessert made with cooked chana dal, jaggery syrup, coconut milk, cardamom, and ghee-roasted cashews.' },
          { name: 'Boorelu', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 270, alt: ['Poornam Boorelu'], desc: 'Festive deep-fried golden dumplings filled with sweet chana dal-jaggery stuffing inside a crispy urad-rice batter shell.' }
        ]
      },
      {
        state: 'Telangana',
        cuisine: 'Hyderabadi Cuisine',
        items: [
          { name: 'Hyderabadi Chicken Dum Biryani', cat: 'Biryani', sub: 'Chicken', veg: false, spice: 'Hot', protein: 38, cal: 580, alt: ['Kachi Dum Biryani'], desc: 'World-famous royal biryani layered with raw spiced chicken, saffron basmati rice, caramelised onions, and slow-dum cooked in sealed handi.' },
          { name: 'Hyderabadi Mutton Dum Biryani', cat: 'Biryani', sub: 'Mutton', veg: false, spice: 'Hot', protein: 42, cal: 640, alt: ['Kachche Gosht Ki Biryani'], desc: 'Celebration biryani made with tender marinated goat meat, aged basmati rice, pure ghee, and saffron.' },
          { name: 'Hyderabadi Haleem', cat: 'Non-Vegetarian', sub: 'Mutton', veg: false, spice: 'Medium', protein: 40, cal: 520, alt: ['Shahi Haleem'], desc: 'Rich royal delicacy of pounded mutton, broken wheat, four lentils, ghee, and aromatic spices cooked into a velvety porridge.' },
          { name: 'Mirchi Ka Salan', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Hot', protein: 6, cal: 260, alt: ['Hyderabadi Chilli Gravy'], desc: 'Nutty and tangy gravy made from roasted peanuts, sesame seeds, coconut, tamarind, and whole fried green chillies.' },
          { name: 'Bagara Rice', cat: 'Rice Dishes', sub: 'Pulao', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 290, alt: ['Telangana Bagara Annam'], desc: 'Fragrant spiced rice tempered with whole garam masala, onions, ginger-garlic, fresh mint, and coriander in ghee.' },
          { name: 'Bagara Baingan', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 240, alt: ['Hyderabadi Spiced Eggplant'], desc: 'Small eggplants simmered in a velvety sauce of roasted peanuts, sesame, coconut, tamarind, and tempered with curry leaves.' },
          { name: 'Sarva Pindi', cat: 'Breakfast', sub: 'Snacks', veg: true, vegan: true, spice: 'Medium', protein: 6, cal: 240, alt: ['Telangana Tapala Chekka'], desc: 'Traditional crispy savory pancake made with rice flour, roasted peanuts, chana dal, sesame seeds, and curry leaves.' },
          { name: 'Sakinalu', cat: 'Snacks', sub: 'Snacks', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 220, alt: ['Sankranti Rice Flour Rings'], desc: 'Traditional concentric spiral snack made from newly harvested raw rice flour, carom seeds, and white sesame, fried golden.' },
          { name: 'Double Ka Meetha', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 8, cal: 380, alt: ['Hyderabadi Bread Pudding'], desc: 'Decadent royal dessert of crisp ghee-fried bread steeped in saffron syrup, layered with thick rabdi and chopped nuts.' },
          { name: 'Qubani Ka Meetha', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 3, cal: 240, alt: ['Apricot Dessert'], desc: 'Classic royal dessert made by stewing dried Turkish apricots in sugar syrup, infused with rose water and served with clotted cream.' },
          { name: 'Osmania Biscuits', cat: 'Snacks', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 3, cal: 160, alt: ['Hyderabadi Chai Biscuits'], desc: 'Iconic sweet and subtly salty butter biscuits served with piping hot Irani Chai in Hyderabadi cafes.' },
          { name: 'Pachi Pulusu', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 1, cal: 85, alt: ['Raw Tamarind Rasam'], desc: 'Refreshing uncooked raw tamarind rasam with direct-flame charred green chillies, onions, coriander, and mustard tadka.' },
          { name: 'Golichina Mamsam', cat: 'Non-Vegetarian', sub: 'Mutton', veg: false, spice: 'Hot', protein: 36, cal: 450, alt: ['Telangana Pan-Fried Mutton Fry'], desc: 'Rustic mutton fry slow-roasted in caramelised onions, ginger-garlic, curry leaves, and freshly ground peppercorn masala.' },
          { name: 'Boti Curry', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Very Hot', protein: 35, cal: 380, alt: ['Telangana Lamb Tripe Curry'], desc: 'Spicy traditional delicacy of tender cleaned lamb tripe simmered with roasted onion paste, garlic, and red chillies.' },
          { name: 'Jonna Rotte', cat: 'Roti & Paratha', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 6, cal: 180, alt: ['Jowar Bhakri', 'Sorghum Flatbread'], desc: 'Nutritious gluten-free flatbread hand-patted from boiling water and sorghum (jowar) flour, roasted on an earthen tawa.' },
          { name: 'Kobbari Kura', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 210, alt: ['Fresh Coconut Curry'], desc: 'Subtly spiced fresh coconut curry cooked with green chillies, mustard seeds, and curry leaves.' },
          { name: 'Makka Garelu', cat: 'Breakfast', sub: 'Vada', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 230, alt: ['Corn Vada Telangana Style'], desc: 'Crispy fried savory fritters made from fresh sweet corn kernels ground with ginger, green chillies, and cumin.' },
          { name: 'Polelu', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 260, alt: ['Telangana Sweet Flatbread'], desc: 'Paper-thin festive flatbread filled with slow-cooked jaggery and roasted chana dal paste.' },
          { name: 'Railu Palaharam', cat: 'Breakfast', sub: 'Snacks', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 190, alt: ['Steamed Rice Flour Dumplings'], desc: 'Steamed rice flour gnocchi-like dumplings tossed with mustard seeds, chana dal, green chillies, and grated coconut.' },
          { name: 'Oorru Kodi Kura', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Very Hot', protein: 38, cal: 430, alt: ['Village Country Chicken Curry'], desc: 'Rustic Telangana village-style free-range chicken curry simmered with whole spices, shallots, and red chilli paste.' },
          { name: 'Phirni Hyderabadi', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 280, alt: ['Rice & Almond Pudding'], desc: 'Creamy ground rice pudding slow-simmered in whole milk with saffron, cardamom, and served in earthen clay Shikoras.' },
          { name: 'Irani Chai', cat: 'Drinks', sub: 'Drinks', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 120, alt: ['Hyderabadi Dum Tea'], desc: 'Rich, velvety black tea decoction combined with slow-condensed creamy milk, cardamom, and sugar.' },
          { name: 'Hyderabadi Luqmi', cat: 'Snacks', sub: 'Mutton', veg: false, spice: 'Medium', protein: 16, cal: 320, alt: ['Minced Meat Pastry Samosa'], desc: 'Crispy square flaky pastry stuffed with spicy minced mutton (keema) sautéed with ginger, mint, and spices.' },
          { name: 'Dum Ka Murgh', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Medium', protein: 36, cal: 440, alt: ['Slow Dum Cooked Chicken'], desc: 'Whole chicken pieces slow-cooked in a rich paste of cashews, almonds, poppy seeds, fried onions, and yogurt on dum.' },
          { name: 'Tala Hua Gosht', cat: 'Non-Vegetarian', sub: 'Mutton', veg: false, spice: 'Hot', protein: 38, cal: 410, alt: ['Hyderabadi Fried Mutton'], desc: 'Crispy, pan-fried boneless mutton cubes tossed with green chillies, curry leaves, ginger, and black pepper.' }
        ]
      },
      {
        state: 'Tamil Nadu',
        cuisine: 'Tamil Cuisine',
        items: [
          { name: 'Crispy Masala Dosa', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: true, spice: 'Medium', protein: 8, cal: 320, alt: ['Madras Masala Dosa'], desc: 'Golden crisp fermented crepe spread with butter, filled with spiced mashed potato bhaji, and served with coconut chutney.' },
          { name: 'Idli Sambar', cat: 'Breakfast', sub: 'Idli', veg: true, vegan: true, spice: 'Medium', protein: 12, cal: 260, alt: ['Steamed Rice Cakes with Sambar'], desc: 'Pillowy steamed rice-lentil cakes soaked in a fragrant vegetable, toor dal, and tamarind sambar.' },
          { name: 'Medu Vada', cat: 'Breakfast', sub: 'Vada', veg: true, vegan: true, spice: 'Medium', protein: 9, cal: 240, alt: ['Crispy Lentil Doughnut'], desc: 'Crispy golden urad dal fritters studded with crushed black pepper, ginger, curry leaves, and green chillies.' },
          { name: 'Chettinad Chicken Curry', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Very Hot', protein: 38, cal: 410, alt: ['Kozhi Chettinad'], desc: 'Fiery chicken curry prepared with freshly roasted whole spices, kalpasi (stone flower), coconut, and black peppercorns.' },
          { name: 'Ven Pongal', cat: 'Breakfast', sub: 'Rice Dishes', veg: true, vegan: false, spice: 'Mild', protein: 9, cal: 310, alt: ['Ghee Pongal'], desc: 'Comforting porridge of rice and moong dal tempered with black pepper, cumin, fresh ginger, crunchy cashews, and ghee.' },
          { name: 'Sambar Sadam', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 8, cal: 330, alt: ['Sambar Rice'], desc: 'One-pot harmony of rice, toor dal, drumsticks, carrots, shallots, and homemade sambar masala with ghee.' },
          { name: 'Tomato Rasam', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 3, cal: 75, alt: ['Thakkali Rasam'], desc: 'Digestive and soothing tomato-tamarind broth infused with crushed black pepper, cumin, garlic, and fresh coriander.' },
          { name: 'Kozhukattai', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 180, alt: ['Modak Tamil Style'], desc: 'Steamed rice flour dumplings filled with grated fresh coconut, organic jaggery, cardamom, and nutmeg.' },
          { name: 'Kothu Parotta', cat: 'Street Food', sub: 'Roti & Paratha', veg: false, spice: 'Hot', protein: 22, cal: 480, alt: ['Shredded Flaky Bread Fry'], desc: 'Flaky layered parottas shredded and stir-fried on a smoking hot iron griddle with eggs, chicken salna, and onions.' },
          { name: 'Karaikudi Fish Fry', cat: 'Seafood', sub: 'Fish', veg: false, spice: 'Hot', protein: 30, cal: 270, alt: ['Chettinad Fish Fry'], desc: 'Fish steaks marinated in a stone-ground paste of red chillies, fennel, garlic, lemon, and shallow-fried in coconut oil.' },
          { name: 'Lemon Rice', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 290, alt: ['Elumichai Sadam'], desc: 'Piquant yellow rice seasoned with fresh lemon juice, crunchy peanuts, mustard seeds, green chillies, and curry leaves.' },
          { name: 'Curd Rice', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 230, alt: ['Thayir Sadam', 'Daddojanam'], desc: 'Soothing creamy rice mixed with fresh homemade yogurt, tempered with mustard, ginger, green chillies, and pomegranate pearls.' },
          { name: 'Filter Coffee', cat: 'Drinks', sub: 'Drinks', veg: true, vegan: false, spice: 'Mild', protein: 3, cal: 95, alt: ['Madras Kaapi'], desc: 'Strong, frothy chicory-infused coffee brewed in a traditional brass filter, combined with boiling whole milk and served in a dabara-set.' },
          { name: 'Kuzhi Paniyaram', cat: 'Breakfast', sub: 'Snacks', veg: true, vegan: true, spice: 'Mild', protein: 6, cal: 190, alt: ['Appe', 'Paddu'], desc: 'Crispy outside, fluffy inside fermented batter dumplings pan-fried in a special indented cast iron paniyaram skillet.' },
          { name: 'Thalappakatti Mutton Biryani', cat: 'Biryani', sub: 'Mutton', veg: false, spice: 'Hot', protein: 38, cal: 590, alt: ['Dindigul Biryani'], desc: 'Famous Dindigul biryani cooked with tiny fragrant Seeraga Samba rice, tender mutton, whole spices, and shallot paste.' },
          { name: 'Chettinad Mutton Chukka', cat: 'Non-Vegetarian', sub: 'Mutton', veg: false, spice: 'Very Hot', protein: 36, cal: 430, alt: ['Mutton Dry Fry'], desc: 'Succulent boneless mutton cubes pan-roasted in black pepper, shallots, garlic, and curry leaves until dry and caramelised.' },
          { name: 'Mor Kuzhambu', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 160, alt: ['Tamil Buttermilk Curry'], desc: 'Creamy spiced yogurt curry cooked with white pumpkin (ash gourd) and ground coconut-cumin-chilli paste.' },
          { name: 'Paruppu Urundai Kuzhambu', cat: 'Curries', sub: 'Dal', veg: true, vegan: true, spice: 'Hot', protein: 12, cal: 260, alt: ['Lentil Dumpling Curry'], desc: 'Steamed spiced toor and chana dal balls simmered in a tangy tamarind-shallot-tomato gravy (Kara Kuzhambu).' },
          { name: 'Poondu Rasam', cat: 'Soups', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 2, cal: 80, alt: ['Garlic Rasam'], desc: 'Medicinal and aromatic garlic rasam prepared with roasted whole garlic cloves, pepper, cumin, and tamarind.' },
          { name: 'Adai Avial', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: true, spice: 'Medium', protein: 14, cal: 330, alt: ['Mixed Lentil Crepe'], desc: 'Hearty thick protein crepe made of four lentils and rice, seasoned with red chillies, asafoetida, and served with Avial.' },
          { name: 'Thirunelveli Halwa', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 370, alt: ['Wheat Halwa'], desc: 'Legendary glossy jelly-like halwa made from fermented whole wheat milk slow-stirred with caramelized sugar and ghee.' },
          { name: 'Paal Payasam', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 8, cal: 280, alt: ['Temple Rice Milk Pudding'], desc: 'Divine temple dessert prepared by slow-reducing full cream milk with raw rice and sugar to a soft pink hue.' },
          { name: 'Kambu Koozh', cat: 'Breakfast', sub: 'Drinks', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 170, alt: ['Pearl Millet Porridge'], desc: 'Fermented pearl millet porridge mixed with buttermilk, chopped shallots, and green chillies, served during hot summer.' },
          { name: 'Vendakkai Mandi', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 4, cal: 160, alt: ['Chettinad Okra Stew'], desc: 'Chettinad okra delicacy cooked in rice-water starch (mandi), shallots, garlic, and mild tamarind.' },
          { name: 'Vazhaipoo Poriyal', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 130, alt: ['Banana Flower Stir Fry'], desc: 'Nutritious banana blossoms finely chopped and stir-fried with mustard, chana dal, fresh coconut, and curry leaves.' }
        ]
      },
      {
        state: 'Kerala',
        cuisine: 'Kerala Cuisine',
        items: [
          { name: 'Appam with Vegetable Stew', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: true, spice: 'Mild', protein: 6, cal: 280, alt: ['Palappam with Ishtu'], desc: 'Lacy, bowl-shaped fermented rice crepes with a soft pillowy center, served with a gentle coconut milk vegetable stew.' },
          { name: 'Puttu and Kadala Curry', cat: 'Breakfast', sub: 'Curries', veg: true, vegan: true, spice: 'Hot', protein: 15, cal: 340, alt: ['Steamed Rice Cake with Black Chickpeas'], desc: 'Steamed ground rice and grated coconut cylinders served with a spicy roasted coconut black chickpea gravy.' },
          { name: 'Kerala Parotta with Chicken Fry', cat: 'Street Food', sub: 'Chicken', veg: false, spice: 'Hot', protein: 32, cal: 540, alt: ['Malabar Porotta Chicken'], desc: 'Multi-layered flaky coiled parottas served with spicy shallow-fried country chicken and rich salna.' },
          { name: 'Karimeen Pollichathu', cat: 'Seafood', sub: 'Fish', veg: false, spice: 'Hot', protein: 32, cal: 310, alt: ['Pearl Spot in Banana Leaf'], desc: 'Backwater Pearl Spot fish marinated in spicy masala, shallow fried, smothered in shallot gravy, wrapped in banana leaf, and pan-roasted.' },
          { name: 'Thalassery Biryani', cat: 'Biryani', sub: 'Chicken', veg: false, spice: 'Medium', protein: 36, cal: 520, alt: ['Malabar Dum Biryani'], desc: 'Aromatic coastal biryani made with fragrant small-grain Kaima rice, ghee, tender chicken, cashews, raisins, and fried onions.' },
          { name: 'Kerala Avial', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 190, alt: ['Sadya Mixed Vegetable Stew'], desc: 'Sadya centerpiece of thirteen indigenous vegetables cooked with raw coconut-cumin-chilli paste and finished with coconut oil and curd.' },
          { name: 'Cabbage Thoran', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 140, alt: ['Cabbage Coconut Stir Fry'], desc: 'Finely shredded cabbage tossed with fresh grated coconut, green chillies, shallots, mustard seeds, and curry leaves.' },
          { name: 'Olan', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 150, alt: ['Ash Gourd & Red Beans in Coconut Milk'], desc: 'Subtle Sadya stew of white ash gourd and red cowpeas simmered in light coconut milk and drizzled with virgin coconut oil.' },
          { name: 'Ada Pradhaman', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: true, spice: 'Mild', protein: 3, cal: 310, alt: ['Rice Flake Jaggery Pudding'], desc: 'The king of Kerala payasams made from steamed rice flakes (ada) cooked in dark jaggery syrup, coconut milk, and dry ginger.' },
          { name: 'Kerala Banana Chips', cat: 'Snacks', sub: 'Snacks', veg: true, vegan: true, spice: 'Mild', protein: 2, cal: 210, alt: ['Nendran Upperi'], desc: 'Crisp, golden discs of raw Nendran bananas deep fried in pure unrefined coconut oil with turmeric and salt.' },
          { name: 'Moru Curry', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 130, alt: ['Kerala Spiced Buttermilk Curry'], desc: 'Comforting sour yogurt curry seasoned with ground coconut, ginger, green chillies, garlic, and fenugreek.' },
          { name: 'Erissery', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 6, cal: 210, alt: ['Pumpkin and Red Cowpeas Curry'], desc: 'Traditional Sadya dish of sweet yellow pumpkin and red beans in coconut paste, topped with deep golden toasted coconut.' },
          { name: 'Meen Moilee', cat: 'Curries', sub: 'Fish', veg: false, spice: 'Mild', protein: 28, cal: 320, alt: ['Kerala Fish Stew in Coconut Milk'], desc: 'Delicate Anglo-Indian fish stew simmered in creamy coconut milk with ginger, green chillies, tomatoes, and curry leaves.' },
          { name: 'Kerala Egg Roast', cat: 'Curries', sub: 'Egg', veg: false, spice: 'Hot', protein: 14, cal: 240, alt: ['Mutta Roast'], desc: 'Hard-boiled eggs coated in a caramelized thick onion, tomato, ginger-garlic, and black pepper masala.' },
          { name: 'Pathiri', cat: 'Roti & Paratha', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 160, alt: ['Malabar Rice Flatbread'], desc: 'Silky smooth, paper-thin steamed and roasted rice flour pancakes from the Malabar coast, paired with chicken or fish curry.' },
          { name: 'Unniyappam', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: true, spice: 'Mild', protein: 3, cal: 190, alt: ['Fried Banana Jaggery Fritters'], desc: 'Mini golden spongy fritters made from soaked rice, ripe small bananas, melted jaggery, cardamom, and roasted coconut bits.' },
          { name: 'Neyyappam', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 3, cal: 220, alt: ['Ghee Fried Rice Cake'], desc: 'Deep-brown sweet fritters made with ground rice, jaggery, and cardamom, fried in pure desi ghee.' },
          { name: 'Palada Payasam', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 290, alt: ['Rice Ada Milk Payasam'], desc: 'Creamy pink payasam made by slow cooking fine rice ada in whole milk and sugar for over two hours.' },
          { name: 'Pineapple Pachadi', cat: 'Chutneys', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 3, cal: 160, alt: ['Sweet & Sour Pineapple Curry'], desc: 'Sadya specialty of cooked pineapple cubes in ground coconut-mustard paste and whisked sour yogurt.' },
          { name: 'Theeyal', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 4, cal: 210, alt: ['Toasted Coconut Stew with Shallots'], desc: 'Deep dark aromatic curry made with shallots simmered in tamarind and freshly toasted dark brown coconut-spice paste.' }
        ]
      },
      {
        state: 'Karnataka',
        cuisine: 'Karnataka & Udupi Cuisine',
        items: [
          { name: 'Bisi Bele Bath', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 9, cal: 360, alt: ['Hot Lentil Rice Karnataka Style'], desc: 'Iconic one-pot meal of rice, toor dal, mixed vegetables, tamarind, and freshly ground spice blend with marathi moggu and copra.' },
          { name: 'Mysore Masala Dosa', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: false, spice: 'Medium', protein: 8, cal: 350, alt: ['Red Chutney Mysore Dosa'], desc: 'Thick and crisp Mysore crepe smeared with spicy red garlic-chilli chutney, butter, and stuffed with potato palya.' },
          { name: 'Mysore Pak', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 390, alt: ['Royal Mysore Gram Flour Sweet'], desc: 'Melt-in-mouth royal confection crafted from roasted gram flour, sugar syrup, and copious smoking-hot pure ghee.' },
          { name: 'Akki Roti', cat: 'Breakfast', sub: 'Roti & Paratha', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 220, alt: ['Karnataka Rice Flatbread'], desc: 'Crispy rustic rice flour flatbread kneaded with fresh dill leaves, onions, grated carrots, green chillies, and cumin.' },
          { name: 'Ragi Mudde with Saaru', cat: 'Lunch', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 8, cal: 260, alt: ['Finger Millet Balls with Broth'], desc: 'Traditional steamed finger millet (ragi) balls swallowed with spicy, aromatic lentil-greens saaru.' },
          { name: 'Mangalorean Fish Curry', cat: 'Curries', sub: 'Fish', veg: false, spice: 'Hot', protein: 32, cal: 340, alt: ['Meen Gassi'], desc: 'Tangy and fiery coastal fish curry simmered in a stone-ground paste of Byadagi chillies, coriander, coconut, and tamarind.' },
          { name: 'Neer Dosa', cat: 'Breakfast', sub: 'Dosa', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 170, alt: ['Water Dosa'], desc: 'Feather-light, delicate, and lace-soft unfermented crepes made from fine rice and coconut water batter.' },
          { name: 'Kundapura Chicken Curry', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Hot', protein: 36, cal: 390, alt: ['Coastal Karnataka Chicken'], desc: 'Coastal chicken curry prepared with a fragrant roasted spice paste of Byadagi chillies, coriander seeds, and coconut milk.' },
          { name: 'Maddur Vada', cat: 'Snacks', sub: 'Vada', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 230, alt: ['Crispy Maddur Fritter'], desc: 'Crunchy savory tea-time fritters made from semolina, rice flour, maida, sliced onions, curry leaves, and green chillies.' },
          { name: 'Dharwad Peda', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 280, alt: ['Caramelised Milk Sweet'], desc: 'Famous heritage sweet made from slow-caramelized milk khoya, sugar, and dusted in powdered sugar.' },
          { name: 'Jolada Roti with Yennegai', cat: 'Roti & Paratha', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Hot', protein: 8, cal: 310, alt: ['Jowar Roti with Stuffed Brinjal'], desc: 'North Karnataka sorghum flatbread served with fiery peanut and sesame stuffed baby eggplant curry.' },
          { name: 'Kesari Bath', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 260, alt: ['Saffron Semolina Halwa'], desc: 'Aromatic sweet pudding made from roasted semolina (rava), pure ghee, saffron strands, sugar, and golden cashews.' },
          { name: 'Kori Rotti', cat: 'Non-Vegetarian', sub: 'Chicken', veg: false, spice: 'Hot', protein: 34, cal: 450, alt: ['Crisp Rice Wafers with Chicken Curry'], desc: 'Unique Tuluva dish of crisp sun-dried rice wafers soaked in hot, spicy coconut-rich chicken gravy.' },
          { name: 'Chitranna', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 280, alt: ['Karnataka Lemon Rice'], desc: 'Steamed rice tossed with roasted peanuts, mustard seeds, green chillies, turmeric, curry leaves, and fresh lime juice.' },
          { name: 'Mangalore Buns', cat: 'Breakfast', sub: 'Roti & Paratha', veg: true, vegan: true, spice: 'Mild', protein: 5, cal: 240, alt: ['Banana Puri'], desc: 'Mildly sweet, fluffy, and pillowy deep-fried puris made from ripe bananas, flour, and yogurt.' }
        ]
      }
    ]
  },

  // 2. NORTH INDIA (Punjab, Uttar Pradesh, Delhi, Rajasthan, Haryana, Himachal Pradesh, Uttarakhand, Jammu & Kashmir)
  {
    region: 'North Indian',
    states: [
      {
        state: 'Punjab',
        cuisine: 'Punjabi Cuisine',
        items: [
          { name: 'Butter Chicken (Murgh Makhani)', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Mild', protein: 36, cal: 480, alt: ['Murgh Makhani', 'Classic Butter Chicken'], desc: 'The world-famous Punjabi classic: tandoori-grilled chicken pieces simmered in a velvety, buttery tomato gravy with cashews and dried fenugreek (kasuri methi).' },
          { name: 'Chicken Tikka Masala', cat: 'Curries', sub: 'Chicken', veg: false, spice: 'Medium', protein: 38, cal: 450, alt: ['Tikka Masala'], desc: 'Smoky char-grilled chicken tikka chunks cooked in a robust spiced tomato, onion, and bell pepper masala sauce.' },
          { name: 'Dal Makhani', cat: 'Dal', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 14, cal: 340, alt: ['Creamy Black Lentil Dal'], desc: 'Whole black urad dal and kidney beans slow-simmered overnight on charcoal with butter, cream, and Kashmiri chilli.' },
          { name: 'Sarson Ka Saag & Makki Di Roti', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 9, cal: 360, alt: ['Mustard Greens with Corn Bread'], desc: 'Rustic winter feast of slow-cooked mustard greens, bathua, and spinach topped with white butter, served with cornmeal flatbread and jaggery.' },
          { name: 'Amritsari Kulcha', cat: 'Roti & Paratha', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 8, cal: 320, alt: ['Stuffed Amritsari Naan'], desc: 'Crisp, layered, flaky tandoor-baked bread stuffed with spiced potatoes, onions, anardana (pomegranate seeds), and loaded with desi ghee.' },
          { name: 'Chole Bhature', cat: 'Breakfast', sub: 'Street Food', veg: true, vegan: true, spice: 'Hot', protein: 16, cal: 560, alt: ['Spicy Chickpeas with Puffed Bread'], desc: 'Dark, spicy, tangy Amritsari chickpea curry paired with giant golden deep-fried puffed bhature bread and pickled onions.' },
          { name: 'Paneer Tikka', cat: 'Snacks', sub: 'Paneer', veg: true, vegan: false, spice: 'Medium', protein: 18, cal: 320, alt: ['Tandoori Paneer Skewers'], desc: 'Succulent cubes of fresh cottage cheese, bell peppers, and onions marinated in spiced mustard oil yogurt, grilled in a tandoor.' },
          { name: 'Tandoori Chicken', cat: 'Snacks', sub: 'Chicken', veg: false, spice: 'Medium', protein: 42, cal: 380, alt: ['Punjabi Tandoori Murgh'], desc: 'Whole bone-in chicken marinated in hung curd, Kashmiri red chilli, and tandoori spices, roasted in clay oven with smoky char marks.' },
          { name: 'Rajma Chawal', cat: 'Dal', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 14, cal: 380, alt: ['Red Kidney Bean Curry with Rice'], desc: 'Comforting Punjabi red kidney beans slow-cooked in a thick, fragrant onion-tomato-ginger gravy served over fluffy basmati rice.' },
          { name: 'Kadhi Pakora', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 10, cal: 290, alt: ['Yogurt Kadhi with Onion Fritters'], desc: 'Tangy and creamy gram flour-yogurt curry simmered with crispy onion fritters (pakoras) and tempered with dry red chillies and fenugreek.' },
          { name: 'Baingan Bharta', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 190, alt: ['Smoky Roasted Eggplant Mash'], desc: 'Charcoal fire-roasted eggplant mashed and sautéed with green peas, onions, tomatoes, green chillies, and ginger.' },
          { name: 'Aloo Paratha', cat: 'Breakfast', sub: 'Roti & Paratha', veg: true, vegan: false, spice: 'Medium', protein: 7, cal: 310, alt: ['Spiced Potato Stuffed Flatbread'], desc: 'Whole wheat flatbread stuffed with spiced mashed potatoes, roasted on a tawa with ghee and served with fresh homemade butter and pickle.' },
          { name: 'Paneer Butter Masala', cat: 'Curries', sub: 'Paneer', veg: true, vegan: false, spice: 'Mild', protein: 18, cal: 420, alt: ['Paneer Makhani'], desc: 'Soft cottage cheese cubes simmered in a luscious creamy tomato gravy with butter, cashews, and aromatic spices.' },
          { name: 'Palak Paneer', cat: 'Curries', sub: 'Paneer', veg: true, vegan: false, spice: 'Medium', protein: 17, cal: 310, alt: ['Cottage Cheese in Spinach Gravy'], desc: 'Fresh paneer cubes gently cooked in a velvety, vibrant green spinach puree infused with garlic, cumin, and cream.' },
          { name: 'Sweet Punjabi Lassi', cat: 'Drinks', sub: 'Drinks', veg: true, vegan: false, spice: 'Mild', protein: 8, cal: 240, alt: ['Creamy Yogurt Cooler'], desc: 'Thick, churned sweet yogurt drink flavored with rose water, cardamom, topped with a thick layer of clotted cream (malai).' },
          { name: 'Gajar Ka Halwa', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 340, alt: ['Gajrela', 'Carrot Pudding'], desc: 'Classic winter dessert made by slow-cooking grated red Delhi carrots in full-cream milk, khoya, pure ghee, and nuts.' },
          { name: 'Pindi Chole', cat: 'Curries', sub: 'Dal', veg: true, vegan: true, spice: 'Hot', protein: 15, cal: 310, alt: ['Dry Spiced Chickpeas Rawalpindi Style'], desc: 'Rustic dark brown chickpeas cooked dry with roasted pomegranate seeds, carom seeds, amchur, and green chillies.' },
          { name: 'Amritsari Fish Fry', cat: 'Seafood', sub: 'Fish', veg: false, spice: 'Hot', protein: 28, cal: 260, alt: ['Besan Batter Fried Fish'], desc: 'Crispy river sole or singhara fish coated in spiced carom seed (ajwain) and gram flour batter, deep fried golden.' }
        ]
      },
      {
        state: 'Uttar Pradesh & Delhi',
        cuisine: 'Awadhi & Mughlai Cuisine',
        items: [
          { name: 'Awadhi Dum Biryani', cat: 'Biryani', sub: 'Mutton', veg: false, spice: 'Medium', protein: 38, cal: 590, alt: ['Lucknowi Mutton Biryani'], desc: 'Royal Lucknowi biryani made by cooking mutton in aromatic yakhni stock, layered with long basmati rice, ittar, and saffron on slow dum.' },
          { name: 'Galouti Kebab', cat: 'Snacks', sub: 'Mutton', veg: false, spice: 'Mild', protein: 28, cal: 380, alt: ['Melt-in-Mouth Lucknowi Kebab'], desc: 'Legendary Awadhi minced lamb kebabs marinated with raw papaya and 40 royal spices, pan-fried to melt effortlessly on the tongue.' },
          { name: 'Shahi Paneer', cat: 'Curries', sub: 'Paneer', veg: true, vegan: false, spice: 'Mild', protein: 16, cal: 390, alt: ['Royal Cottage Cheese Curry'], desc: 'Royal Mughlai preparation of cottage cheese in a thick, fragrant gravy of cashews, almonds, saffron, and aromatic spices.' },
          { name: 'Bedmi Poori with Rasedar Aloo', cat: 'Breakfast', sub: 'Roti & Paratha', veg: true, vegan: true, spice: 'Hot', protein: 9, cal: 420, alt: ['Lentil Stuffed Poori with Potato Curry'], desc: 'Crisp urad dal-stuffed whole wheat pooris served with spicy, tangy, soupy Banarasi potato curry.' },
          { name: 'Banarasi Dum Aloo', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 6, cal: 280, alt: ['Stuffed Potato Curry Banaras Style'], desc: 'Deep-fried baby potatoes scooped and stuffed with spiced paneer and nuts, simmered in rich tomato gravy.' },
          { name: 'Petha', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: true, spice: 'Mild', protein: 1, cal: 180, alt: ['Agra Petha', 'Candied Ash Gourd'], desc: 'Famous translucent sweet from Agra made by candying winter melon (ash gourd) in cardamom and saffron sugar syrup.' },
          { name: 'Tehri', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 6, cal: 310, alt: ['Awadhi Vegetable Pulao'], desc: 'Fragrant yellow rice one-pot dish cooked with potatoes, cauliflower, peas, turmeric, and mustard oil.' },
          { name: 'Malaiyyo', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 190, alt: ['Banarasi Dew Froth Dessert', 'Makhan Malai'], desc: 'Ethereal winter dessert made by churning dew-chilled milk into cloud-like saffron foam garnished with pistachios.' },
          { name: 'Matar Nimona', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 9, cal: 220, alt: ['Fresh Green Pea Curry UP Style'], desc: 'Rustic UP winter curry made from coarsely ground fresh sweet green peas, baby potatoes, and cumin-coriander masala.' },
          { name: 'Mathura Peda', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 290, alt: ['Caramelised Milk Fudge'], desc: 'Traditional dark brown fudge made from slow-roasted khoya, powdered sugar, and fragrant cardamom.' },
          { name: 'Imarti', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 310, alt: ['Jangiri', 'Circular Lentil Sweet'], desc: 'Intricate circular flower-patterned sweet made from ground urad dal batter, deep fried crisp and soaked in saffron syrup.' },
          { name: 'Lucknowi Mutton Korma', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Medium', protein: 36, cal: 490, alt: ['Shahi Gosht Korma'], desc: 'Slow-simmered tender mutton in a velvety gravy of fried onions, yogurt, cashew paste, kewra water, and whole spices.' },
          { name: 'Nihari Gosht', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Hot', protein: 40, cal: 540, alt: ['Old Delhi Slow Cooked Shank Stew'], desc: 'Overnight slow-cooked mutton shank stew flavored with potli masala, fennel, ginger, and thickened with roasted flour.' },
          { name: 'Banarasi Tamatar Chaat', cat: 'Street Food', sub: 'Snacks', veg: true, vegan: true, spice: 'Hot', protein: 5, cal: 210, alt: ['Kashi Tomato Chaat'], desc: 'Spicy mashed tomatoes and potatoes cooked on a tawa with spices, topped with sugar syrup, namkeen, and cilantro.' },
          { name: 'Shahi Tukda', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 360, alt: ['Royal Saffron Bread Sweet'], desc: 'Crispy ghee-fried bread steeped in saffron sugar syrup and smothered in thick creamy cardamom rabdi.' }
        ]
      },
      {
        state: 'Rajasthan',
        cuisine: 'Rajasthani Cuisine',
        items: [
          { name: 'Dal Baati Churma', cat: 'Lunch', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 16, cal: 580, alt: ['Classic Rajasthani Baati Feast'], desc: 'The signature Rajasthani platter of spicy five-lentil dal, hard wheat flour dough balls baked over charcoal and dipped in pure ghee, served with sweet jaggery churma.' },
          { name: 'Laal Maas', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Very Hot', protein: 38, cal: 480, alt: ['Rajasthani Red Mutton Curry'], desc: 'Royal warrior curry of tender mutton slow-cooked in a fiery paste of soaked Mathania red chillies, garlic, and ghee with charcoal dhungar smoke.' },
          { name: 'Ker Sangri', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 7, cal: 240, alt: ['Desert Bean and Berry Sabzi'], desc: 'Traditional Marwari desert delicacy made from dried desert wild beans (sangri) and caper berries (ker) cooked with whole red chillies and dry mango.' },
          { name: 'Rajasthani Gatte Ki Sabzi', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 11, cal: 280, alt: ['Gram Flour Dumplings in Spiced Yogurt'], desc: 'Steamed gram flour dumplings sliced and simmered in a spiced, velvety curd gravy tempered with mustard, cumin, and hing.' },
          { name: 'Pyaaz Kachori', cat: 'Street Food', sub: 'Snacks', veg: true, vegan: true, spice: 'Medium', protein: 6, cal: 290, alt: ['Jodhpur Onion Kachori'], desc: 'Flaky, golden, crisp deep-fried pastry generously filled with a spicy, caramelized onion, fennel, and coriander seed stuffing.' },
          { name: 'Ghevar', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 4, cal: 380, alt: ['Honeycomb Saffron Sweet'], desc: 'Intricate honeycomb-patterned disc sweet made from flour and ghee, dipped in sugar syrup and topped with rich mawa, saffron, and silver leaf.' },
          { name: 'Mohan Thaal', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 7, cal: 340, alt: ['Roasted Gram Flour Fudge'], desc: 'Traditional festive fudge made from coarse roasted besan, condensed milk, ghee, cardamom, and chopped almonds.' },
          { name: 'Papad Ki Sabzi', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Medium', protein: 6, cal: 190, alt: ['Crisp Lentil Wafers in Yogurt Gravy'], desc: 'Quick homestyle curry made by cooking roasted or fried urad dal papads in a spiced yogurt-fenugreek sauce.' },
          { name: 'Bajra Roti with Lahsun Ki Chutney', cat: 'Roti & Paratha', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Hot', protein: 7, cal: 270, alt: ['Millet Bread with Spicy Garlic Relish'], desc: 'Nutritious pearl millet flatbread served with fiery stone-ground garlic and red chilli chutney and white butter.' },
          { name: 'Mawa Kachori', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 360, alt: ['Sweet Stuffed Jodhpur Kachori'], desc: 'Crispy deep-fried sweet kachori stuffed with rich khoya, nuts, and cardamom, dunked in fragrant sugar syrup.' },
          { name: 'Mirchi Vada', cat: 'Street Food', sub: 'Snacks', veg: true, vegan: true, spice: 'Hot', protein: 5, cal: 240, alt: ['Jodhpur Stuffed Chilli Fritter'], desc: 'Large mild green chillies stuffed with tangy spiced potato mash, dipped in gram flour batter, and deep fried crunchy.' },
          { name: 'Safed Maas', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Mild', protein: 36, cal: 460, alt: ['Royal White Mutton Curry'], desc: 'Royal delicate mutton curry simmered in a luscious white sauce of cashew nuts, poppy seeds, almond paste, and cardamoms.' },
          { name: 'Moong Dal Halwa', cat: 'Sweets', sub: 'Desserts', veg: true, vegan: false, spice: 'Mild', protein: 8, cal: 420, alt: ['Yellow Lentil Ghee Halwa'], desc: 'Rich celebratory dessert made by patiently roasting yellow moong dal paste in generous pure ghee with milk and nuts.' }
        ]
      },
      {
        state: 'Jammu & Kashmir',
        cuisine: 'Kashmiri Wazwan & Pandit Cuisine',
        items: [
          { name: 'Kashmiri Rogan Josh', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Medium', protein: 36, cal: 460, alt: ['Authentic Rogan Josh'], desc: 'The signature Kashmiri lamb curry slow-cooked in aromatic mustard oil with Kashmiri red chillies, fennel powder, dry ginger (sonth), and ratan jot root for deep crimson hue.' },
          { name: 'Kashmiri Dum Aloo', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Medium', protein: 5, cal: 270, alt: ['Dum Oluv'], desc: 'Baby potatoes pricked, deep-fried golden, and simmered in a silky red gravy of Kashmiri chillies, dry ginger, fennel, and asafoetida without onions or garlic.' },
          { name: 'Mutton Yakhni', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Mild', protein: 34, cal: 410, alt: ['Yogurt Based Lamb Curry'], desc: 'Delicate and fragrant lamb cooked in a thin, creamy yogurt broth infused with crushed black cardamom, dried mint, and fennel.' },
          { name: 'Gustaba', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Mild', protein: 38, cal: 490, alt: ['Silken Meatballs in Velvety Gravy'], desc: 'The grand finale of Kashmiri Wazwan: velvety pounded mutton meatballs simmered in a rich, smooth yogurt and mutton stock sauce.' },
          { name: 'Rista', cat: 'Curries', sub: 'Mutton', veg: false, spice: 'Hot', protein: 38, cal: 470, alt: ['Pounded Mutton Meatballs in Saffron Red Gravy'], desc: 'Tender pounded meatballs cooked in a fiery red, saffron-infused gravy with shallot essence (pran) and ratan jot.' },
          { name: 'Kashmiri Kahwa', cat: 'Drinks', sub: 'Drinks', veg: true, vegan: true, spice: 'Mild', protein: 1, cal: 60, alt: ['Saffron Green Tea with Almonds'], desc: 'Exquisite traditional green tea brewed with saffron strands, whole cinnamon, green cardamom, and served with crushed almonds.' },
          { name: 'Nadru Yakhni', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 6, cal: 210, alt: ['Lotus Stem in Spiced Yogurt'], desc: 'Crisp sliced lotus stems simmered in a delicate yogurt gravy flavored with fennel, dry ginger, and dried mint.' },
          { name: 'Haakh Saag', cat: 'Curries', sub: 'Vegetarian', veg: true, vegan: true, spice: 'Mild', protein: 4, cal: 120, alt: ['Kashmiri Collard Greens'], desc: 'Simple and nourishing Kashmiri collard greens stewed with mustard oil, whole green chillies, asafoetida, and water.' },
          { name: 'Tabak Maaz', cat: 'Non-Vegetarian', sub: 'Mutton', veg: false, spice: 'Mild', protein: 32, cal: 460, alt: ['Crisp Fried Lamb Ribs'], desc: 'Tender lamb ribs simmered in spiced milk and water until tender, then pan-fried in desi ghee until crunchy outside and juicy inside.' },
          { name: 'Kashmiri Modur Pulao', cat: 'Rice Dishes', sub: 'Vegetarian', veg: true, vegan: false, spice: 'Mild', protein: 5, cal: 340, alt: ['Sweet Saffron Rice with Dry Fruits'], desc: 'Sweet aromatic basmati rice cooked with saffron milk, pure ghee, sugar, cinnamon, and loaded with fried almonds, cashews, and raisins.' }
        ]
      }
    ]
  }
];

console.log("Ready to expand dataset to 500+ records...");
